version: "3.9"

services:
  deviq-api:
    build: .
    container_name: deviq-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/ingestion:/app/backend/ingestion